"""Central tunables for Covert Strike: Stage One.

The values here are deliberately conservative so the game stays playable on the
target machine: Windows 8.1, 2 GB RAM, Python 3.10.11, no dedicated GPU.
"""

# ---------------------------------------------------------------- display ----
TITLE = "Covert Strike: Stage One - Silent Depot"

# Internal render buffer. Everything 3D is rasterised at RENDER_W x RENDER_H and
# then scaled up. A small buffer is what makes a software raycaster viable on a
# 2 GB machine with integrated graphics.
RENDER_W = 480
RENDER_H = 270
WINDOW_SCALE = 2                      # 480x270 -> 960x540 window
WINDOW_W = RENDER_W * WINDOW_SCALE
WINDOW_H = RENDER_H * WINDOW_SCALE
TARGET_FPS = 60
MAX_FPS = 60

# Raycaster column width. 2 means two screen pixels share one cast, halving the
# per-frame column count again.
COLUMN_WIDTH = 2
NUM_RAYS = RENDER_W // COLUMN_WIDTH

FOV = 1.0471975511965976              # 60 degrees in radians
HALF_FOV = FOV / 2.0
MAX_DEPTH = 32.0

# ---------------------------------------------------------------- player -----
PLAYER_RADIUS = 0.22
PLAYER_HEIGHT = 1.7
PLAYER_EYE = 1.55
WALK_SPEED = 2.3
RUN_SPEED = 3.9
CROUCH_SPEED = 1.1
CROUCH_EYE = 1.05
STRAFE_SPEED = 2.1
MOUSE_SENSITIVITY = 0.0022
MAX_HEALTH = 100
MAX_ARMOR = 100
PLAYER_START_ARMOR = 30

# Noise generated by the player's own movement. Guards hear these within
# NOISE_RADIUS_WALK / NOISE_RADIUS_RUN.
NOISE_WALK = 3.5
NOISE_RUN = 8.0
NOISE_CROUCH = 1.0

# ---------------------------------------------------------------- weapons ----
# name, damage, fire period (s), spread (rad), magazine, reserve, automatic,
# reload time (s), pellet count, noise radius, recoil kick (rad)
WEAPONS = {
    "knife": dict(
        name="Combat Knife", damage=55.0, fire_period=0.45, spread=0.0,
        mag_size=0, reserve=0, automatic=False, reload_time=0.0,
        pellets=1, noise=0.0, recoil=0.0, melee=True, melee_range=1.4,
    ),
    "pistol": dict(
        name="SD Pistol", damage=26.0, fire_period=0.16, spread=0.010,
        mag_size=15, reserve=120, automatic=False, reload_time=1.3,
        pellets=1, noise=11.0, recoil=0.020,
    ),
    "smg": dict(
        name="MP5", damage=17.0, fire_period=0.075, spread=0.028,
        mag_size=30, reserve=240, automatic=True, reload_time=1.9,
        pellets=1, noise=14.0, recoil=0.014,
    ),
    "shotgun": dict(
        name="Pump Shotgun", damage=13.0, fire_period=0.85, spread=0.085,
        mag_size=8, reserve=48, automatic=False, reload_time=2.4,
        pellets=8, noise=16.0, recoil=0.055,
    ),
    "sniper": dict(
        name="Sniper Rifle", damage=110.0, fire_period=1.4, spread=0.0015,
        mag_size=5, reserve=25, automatic=False, reload_time=2.8,
        pellets=1, noise=18.0, recoil=0.070, scoped=True,
    ),
    "grenade": dict(
        name="Frag Grenade", damage=120.0, fire_period=0.9, spread=0.0,
        mag_size=4, reserve=4, automatic=False, reload_time=0.0,
        pellets=1, noise=22.0, recoil=0.0, thrown=True,
    ),
}
WEAPON_ORDER = ["knife", "pistol", "smg", "shotgun", "sniper", "grenade"]

HITSCAN_RANGE = 40.0
HEADSHOT_MULT = 2.3
GRENADE_FUSE = 2.2
GRENADE_RADIUS = 4.2

# ---------------------------------------------------------------- enemies ----
ENEMY_HEIGHT = 1.8
ENEMY_RADIUS = 0.24
ENEMY_VIEW_DISTANCE = 17.0            # fully lit, unobstructed
ENEMY_FOV = 1.7453292519943295        # 100 degrees
ENEMY_HEARING = 13.0                  # base hearing radius
ALERT_DECAY = 0.14                    # per second, when no contact
# AI states
S_IDLE, S_PATROL, S_SUSPICIOUS, S_INVESTIGATE, S_COMBAT, S_SEARCH, S_DEAD = range(7)
ENEMY_STATE_NAMES = {
    S_IDLE: "IDLE", S_PATROL: "PATROL", S_SUSPICIOUS: "SUSPICIOUS",
    S_INVESTIGATE: "INVESTIGATE", S_COMBAT: "COMBAT", S_SEARCH: "SEARCH",
    S_DEAD: "DEAD",
}
ENEMY_REACTION = 0.42                 # seconds before opening fire
ENEMY_ACCURACY_BASE = 0.62
ENEMY_DAMAGE = 9.0
ENEMY_FIRE_PERIOD = 0.42
ENEMY_MAG = 30
ENEMY_RELOAD = 2.6
CONE_HALF = 0.28                      # aim cone half-width for hitscan

# ---------------------------------------------------------------- cameras ----
CAMERA_FOV = 1.3962634015954636       # 80 degrees
CAMERA_RANGE = 15.0
CAMERA_SWEEP = 1.15                   # radians either side of facing
CAMERA_SWEEP_SPEED = 0.55
CAMERA_ALERT_TIME = 1.7               # seconds of continuous sight -> alarm
ALARM_WAVE_INTERVAL = 999.0           # single wave per grenade-free stage

# ---------------------------------------------------------------- mission ----
EXTRACTION_RADIUS = 1.6
INTERACT_RADIUS = 2.0
INTEL_COUNT = 3

# ---------------------------------------------------------------- audio ------
SAMPLE_RATE = 22050                   # low rate keeps RAM/CPU down
AUDIO_CHANNELS = 28
MUSIC_VOLUME = 0.55
SFX_VOLUME = 0.85

# ---------------------------------------------------------------- colours ----
C_BLACK = (0, 0, 0)
C_WHITE = (255, 255, 255)
C_RED = (200, 40, 40)
C_GREEN = (70, 210, 90)
C_AMBER = (235, 175, 60)
C_CYAN = (90, 200, 220)
C_GREY = (150, 150, 150)
